version: 2.1

executors:
    python_docker:
        docker:
            - image: circleci/python:3.7-node-browsers-legacy

jobs:
    build:
        executor: python_docker
        steps:
            - checkout:
                path: ~/project
            - run:
                command: |
                    ls -al
                    sudo chown -R circleci:circleci .
                    chmod -R +rwx ./ci
                    ./ci/setup.sh
                name: Setup
            - run:
                command: |
                    echo 'Running tests'
                    python -m unittest discover -s tests/ -p "test*.py" -v
                name: Run Tests
            - run:
                command: |
                    mkdir -p reports
                    echo '<p><b>this is a test report</b></p>' > reports/fake_test_report.html
                name: Generate Artifacts
            - run:
                command:
                    echo 'Hello Ankur'
                name: Hello

workflows:
  build_test_deploy:
    jobs:
        - build:
            name: build